[package]
name = "phoenyx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc_vector = { path = "proc_vector" }
numeric = { path = "numeric" }
math_vector = { path = "math_vector" }
