[package]
name = "math_vector"
description = "3D vector class"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc_vector = { path = "../proc_vector" }
numeric = { path = "../numeric" }
