[package]
name = "numeric"
description = "Generic numeric traits"
version = "1.1.0"
edition = "2021"

[package.metadata.docs.rs]
features = ["std"]

[dependencies]
libm = { version = "0.2.0", optional = true }

[features]
default = ["std"]
std = []
i128 = []
